services:
  web:
    build: apache
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./apache/exemplo.lan.conf:/etc/apache2/sites-enabled/exemplo.lan.conf
      - ./apache/certificados/exemplo.lan.pem:/certificados/exemplo.lan.pem
      - ./apache/certificados/exemplo.lan.key:/certificados/exemplo.lan.key
