<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHjHHmJF\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHjHHmJF/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHjHHmJF.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHjHHmJF\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHjHHmJF\appAppKernelProdContainer([
    'container.build_hash' => 'HjHHmJF',
    'container.build_id' => '03600a6c',
    'container.build_time' => 1709635517,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHjHHmJF');
